### PR TITLE
#186 openAuth crashed when going to be closed and then press the cancel button

### LINKED ISSUE #186: openAuth crashed when going to be closed and then press the cancel button
Just the simple codes called `openAuth` cause  APP crashed. It was tested by our QC team.
```js
  const response = await InAppBrowser.openAuth(url, redirect, {
    // iOS Properties
    ephemeralWebSession: false,
    // Android Properties
    showTitle: false,
    enableUrlBarHiding: true,
    enableDefaultShare: false,
  });
```

Happened when the auth modal of InAppBrowser was finished and going to be closed then you pressed the cancel button at the same time.

Need help please.

### PR DESCRIPTION
**Pull request by hikouki**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/proyecto26/react-native-inappbrowser/blob/master/CONTRIBUTING.md#pull-request-process.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] All existing tests are passing
- [ ] Tests for the changes are included

## What is the current behavior?

openAuth crashed when going to be closed and then press the cancel button.

The completionHandler was called, then redirectResolve to be null by flowDidFinish. After that completionHandler be call again by press the cancel button.

redirectResolve is null, and so crash.

## What is the new behavior?

No more crash.

Fixes/Implements/Closes #186.

### CODE REVIEW

File: ios/RNInAppBrowser.m [hunk 1]
```diff
@@ -75,16 +75,18 @@ + (BOOL)requiresMainQueueSetup
...
-          redirectResolve(@{
-            @"type" : @"cancel",
-          });
+        if (redirectResolve) {
+          if (!error) {
+            NSString *url = callbackURL.absoluteString;
+            redirectResolve(@{
+                @"type" : @"success",
+                  @"url" : url,
+                  });
```
Comment (jdnichollsc) [inline ios/RNInAppBrowser.m:84]: hello mate, can you fix indentation please?

**Review by jdnichollsc — COMMENTED** [review]
Thanks for your help Houki, please check my little comment! <3

File: ios/RNInAppBrowser.m (hunk 1 above)
Comment (hikouki) [reply ios/RNInAppBrowser.m]: Hi, Thank you for review!
I fixed it. ✈️

**Comment by jdnichollsc** [comment]
Thanks for your contribution! <3

**Comment by isidoro98** [comment]
Hey @jdnichollsc are you planning on a release with this fix?

Thanks

**Comment by jdnichollsc** [comment]
Today <3
